services:
  client:
    container_name: spring-react-template-client-dev
    image: spring-react-template-client-dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./client
      dockerfile: Dockerfile-dev
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - 3001:3000
    stdin_open: true