services:
  api:
    container_name: spring-react-template-api-dev
    build:
      context: ./api
      dockerfile: Dockerfile-dev
    volumes:
      - ./:/app
      - ./.m2:/root/.m2
    working_dir: /app
    command: sh run.sh
    ports:
      - 8080:8080
      - 35729:35729
      - 5005:5005

  client:
    container_name: spring-react-template-client-dev
    image: spring-react-template-client-dev
    environment:
      CHOKIDAR_USEPOLLING: "true"
    build:
      context: ./client
      dockerfile: Dockerfile-dev
    volumes:
      - node_modules:/home/node/node_modules
      - ./client:/home/node
    ports:
      - 3001:3000

volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: change\absolute\local\path\to\client\node_modules