name: Java CI

on: [push]

jobs:

  coding-standards:
    name: Coding Standards
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: x64
      - name: Run spring javaformat validation
        run: mvn spring-javaformat:validate
